Repository Team-TenTen/LinkHub-FE, pull requests merged in 2023-11, with the labels that each got.

#36 CategoryList 컴포넌트 구현
  src/components/common/CategoryList/CategoryList.tsx
  src/components/common/CategoryList/CategoryListItem.tsx
  src/components/common/CategoryList/constants/index.ts
  src/components/common/CategoryList/hooks/useCategoryList.ts
  src/components/index.ts
Labels: ✨ Feature

#33 Modal 컴포넌트 구현
  src/app/layout.tsx
  src/components/common/Modal/Modal.tsx
  src/components/common/Modal/constants/index.ts
  src/components/common/Modal/hooks/index.ts
  src/components/common/Modal/hooks/useModalLogic.ts
  src/components/index.ts
  src/hooks/index.ts
  src/hooks/useModal.ts
Labels: ✨ Feature

#37 Dropdown 컴포넌트 구현
  src/components/common/Dropdown/Dropdown.tsx
  src/components/common/Dropdown/DropdownItem.tsx
  src/components/common/Dropdown/constants/index.ts
  src/components/common/Dropdown/hooks/useDropdown.ts
  src/components/index.ts
Labels: ✨ Feature

#42 스페이스 멤버 컴포넌트 구현
  src/components/common/SpaceMemberList/SpaceMemberList.tsx
  src/components/common/SpaceMemberList/constants/index.ts
  src/components/index.ts
  src/data/index.ts
Labels: ✨ Feature

#35 헤더 컴포넌트 구현
  src/app/layout.tsx
  src/components/common/Header/Header.tsx
Labels: ✨ Feature

#38 스페이스 생성 form 구현
  public/test-image.svg
  src/app/(routes)/space/[spaceId]/setting/page.tsx
  src/app/(routes)/space/create/page.tsx
  src/components/Space/SpaceForm.tsx
  src/components/Space/constant/index.ts
  src/components/common/CategoryList/CategoryList.tsx
  src/components/common/CategoryList/CategoryListItem.tsx
  src/components/common/CategoryList/hooks/useCategoryList.ts
  src/components/common/Dropdown/Dropdown.tsx
  src/components/common/Dropdown/DropdownItem.tsx
  src/components/common/SpaceMemberList/SpaceMemberList.tsx
  src/components/common/Toggle/Toggle.tsx
Labels: ✨ Feature

#45 댓글 컴포넌트 구현
  src/components/Comment/Comment.tsx
  src/components/index.ts
Labels: ✨ Feature

#48 스페이스 상세 페이지 구현
  package-lock.json
  package.json
  src/app/(routes)/space/[spaceId]/page.tsx
  src/components/common/LinkItem/ constants/index.ts
  src/components/common/LinkItem/LinkItem.tsx
  src/components/common/LinkList/LinkList.tsx
  src/components/common/LinkList/constants/index.ts
  src/components/common/LinkList/hooks/useViewLink.ts
  src/components/common/Modal/Modal.tsx
  src/components/common/Modal/hooks/useModalLogic.ts
  src/components/common/Tab/hooks/useTab.ts
  src/components/common/Tab/utils/index.ts
  src/constants/index.ts
  src/data/index.ts
  src/hooks/index.ts
  src/hooks/useCurrentModal.ts
  src/hooks/useModal.ts
  src/types/index.ts
Labels: ✨ Feature

#44 Sidebar 컴포넌트 구현
  src/app/layout.tsx
  src/components/common/Header/Header.tsx
  src/components/common/Sidebar/Sidebar.tsx
  src/components/common/Sidebar/hooks/useSidebar.ts
  src/components/common/ThemeButton/ThemeButton.tsx
  src/components/index.ts
  src/data/index.ts
Labels: ✨ Feature

#49 스페이스 댓글 페이지 구현
  src/app/(routes)/bomiTest/tabTest/layout.tsx
  src/app/(routes)/space/[spaceId]/comment/page.tsx
  src/app/(routes)/space/[spaceId]/page.tsx
  src/components/Comment/Comment.tsx
  src/components/common/Header/Header.tsx
  src/components/common/Sidebar/Sidebar.tsx
  src/components/common/Tab/Tab.tsx
  src/components/common/Tab/TabItem.tsx
  src/components/common/Tab/hooks/useTab.ts
  src/components/common/Tab/utils/index.ts
  src/data/index.ts
  src/hooks/useSpaceComment.ts
Labels: ✨ Feature

#56 유저 컴포넌트 구현
  src/components/common/Button/Button.tsx
  src/components/common/User/User.tsx
  src/data/index.ts
Labels: ✨ Feature

#51 알림 컴포넌트 구현
  src/app/globals.css
  src/components/common/Notification/Notification.tsx
  src/components/common/Notification/constants/index.ts
  src/components/common/Notification/hooks/useNotification.ts
  src/components/index.ts
  src/data/index.ts
  tailwind.config.ts
Labels: ✨ Feature

#66 메인 페이지 구현
  src/app/(routes)/bomiTest/spaceTest/page.tsx
  src/app/globals.css
  src/app/page.tsx
  src/components/common/CategoryList/CategoryList.tsx
  src/components/common/CategoryList/hooks/useCategoryList.ts
  src/components/common/LinkItem/LinkItem.tsx
  src/components/common/LinkList/LinkList.tsx
  src/components/common/Space/Space.tsx
  src/data/index.ts
  src/hooks/useHome.ts
Labels: ✨ Feature

#65 회원가입 페이지 구현
  src/app/(routes)/register/page.tsx
  src/components/UserInfoForm/UserInfoForm.tsx
  src/components/UserInfoForm/hooks/useRegister.ts
  src/components/common/Avatar/Avatar.tsx
  src/components/common/Input/Input.tsx
  src/data/index.ts
  src/types/index.ts
Labels: ✨ Feature

#59 로그인 페이지 구현
  src/app/(routes)/login/page.tsx
  src/components/Login/Login.tsx
  src/components/Login/hooks/useLogin.ts
Labels: ✨ Feature

#68 API 테스트
  .gitignore
  src/app/(routes)/bomiTest/apiTest/[spaceId]/page.tsx
  src/app/api/space/[spaceId]/route.ts
  src/components/common/Space/Space.tsx
  src/lib/fetchAPI.ts
  src/lib/fetchServerAPI.ts
  src/services/apiServices.ts
  src/services/space/space.ts
Labels: 📬 API

#67 유저 페이지 구현
  package-lock.json
  package.json
  src/app/(routes)/user/[userId]/favorite/page.tsx
  src/app/(routes)/user/[userId]/layout.tsx
  src/app/(routes)/user/[userId]/page.tsx
  src/app/(routes)/user/[userId]/space/page.tsx
  src/components/common/Modal/Modal.tsx
  src/components/common/Tab/utils/index.ts
  src/constants/index.ts
  src/data/index.ts
  src/hooks/useSearch.ts
  src/types/index.ts
  src/utils/index.ts
  tailwind.config.ts
Labels: ✨ Feature

#72 Dropdown 컴포넌트 버그 수정
  src/components/common/Dropdown/Dropdown.tsx
  src/components/common/Dropdown/hooks/useDropdown.ts
Labels: 🐞 Bug

#70 프로필 수정 페이지 구현
  src/app/(routes)/register/page.tsx
  src/app/(routes)/user/setting/page.tsx
  src/components/UserInfoForm/UserInfoForm.tsx
  src/components/common/LinkItem/LinkItem.tsx
  src/components/common/Modal/Modal.tsx
  src/data/index.ts
  src/types/index.ts
Labels: ✨ Feature

#79 CI/CD 워크플로 설정
  .github/workflows/deploy.yml
  appspec.yml
  deploy.sh
  ecosystem.config.js
  package.json
Labels: ⚙ Setting

#81 CI/CD 워크플로 수정
  .github/workflows/deploy.yml
  .github/workflows/pull_request.yml
Labels: ⚙ Setting

#82 [Release] v0.1.1
  .github/workflows/deploy.yml
  .github/workflows/pull_request.yml
Labels: 🌎 Deploy

#83 CI/CD 워크플로 수정
  .github/workflows/deploy.yml
Labels: ⚙ Setting

#84 [Release] v0.1.2
  .github/workflows/deploy.yml
Labels: 🌎 Deploy

#86 CI/CD Test
  .github/workflows/deploy.yml
Labels: 🌎 Deploy

#88 CI/CD Test
  deploy.sh
  ecosystem.config.js
Labels: 🌎 Deploy

#89 CI/CD 워크플로 수정
  .github/workflows/deploy.yml
Labels: ⚙ Setting

#90 CI/CD Test
  .github/workflows/deploy.yml
Labels: 🌎 Deploy

#91 CI/CD 워크플로 수정
  ecosystem.config.js
Labels: ⚙ Setting

#92 CI/CD Test
  ecosystem.config.js
Labels: 🌎 Deploy

#93 CI/CD 워크플로 수정
  appspec.yml
  deploy.sh
  ecosystem.config.js
  package.json
  scripts/after-install.sh
  scripts/application-start.sh
Labels: ⚙ Setting

#94 CI/CD Test
  appspec.yml
  deploy.sh
  ecosystem.config.js
  package.json
  scripts/after-install.sh
  scripts/application-start.sh
Labels: 🌎 Deploy

#95 CI/CD 워크플로 수정
  appspec.yml
Labels: ⚙ Setting

#96 CI/CD Test
  appspec.yml
Labels: 🌎 Deploy

#99 API req/res interface 작성
  src/types/index.ts
Labels: ✨ Feature

#101 링크 생성 api 연결
  src/app/api/link/route.ts
  src/app/api/meta/route.ts
  src/components/common/LinkList/LinkList.tsx
  src/components/common/LinkList/constants/index.ts
  src/components/common/LinkList/hooks/useCreateLink.ts
  src/components/common/Modal/Modal.tsx
  src/constants/index.ts
  src/services/link/link.ts
  src/services/meta/meta.ts
  src/types/index.ts
  src/utils/index.ts
Labels: 📬 API

#106 메인 스페이스 조회 api 연결
  next.config.js
  src/app/(routes)/space/[spaceId]/setting/page.tsx
  src/app/api/spaces/route.ts
  src/app/page.tsx
  src/components/Space/SpaceForm.tsx
  src/components/UserInfoForm/UserInfoForm.tsx
  src/components/common/CategoryList/CategoryList.tsx
  src/components/common/CategoryList/CategoryListItem.tsx
  src/components/common/CategoryList/constants/index.ts
  src/components/common/Dropdown/constants/index.ts
  src/constants/index.ts
  src/data/index.ts
  src/hooks/useHome.ts
  src/hooks/useSearch.ts
  src/services/space/spaces.ts
  src/types/index.ts
Labels: 📬 API

#108 스페이스 상세 조회 api 연결
  src/app/(routes)/bomiTest/apiTest/[spaceId]/page.tsx
  src/app/(routes)/bomiTest/spaceTest/page.tsx
  src/app/(routes)/space/[spaceId]/comment/page.tsx
  src/app/(routes)/space/[spaceId]/page.tsx
  src/app/api/space/[spaceId]/route.ts
  src/components/common/Space/Space.tsx
  src/components/common/Space/hooks/useGetSpace.ts
  src/components/common/SpaceMemberList/SpaceMemberList.tsx
  src/components/common/Tab/hooks/useTab.ts
  src/components/common/Tab/utils/index.ts
  src/constants/index.ts
  src/data/index.ts
  src/services/space/space.ts
Labels: 📬 API

#100 스페이스 생성 API
  src/app/api/spaces/create/route.ts
  src/components/Space/SpaceForm.tsx
  src/components/common/Space/hooks/useGetSpace.ts
  src/constants/index.ts
  src/lib/fetchAPI.ts
  src/lib/fetchServerAPI.ts
  src/services/space/space.ts
  src/types/index.ts
Labels: 📬 API

#110 로그인 및 회원가입 API 연결
  next.config.js
  package-lock.json
  package.json
  src/app/(routes)/user/setting/page.tsx
  src/app/api/auth-user/route.ts
  src/app/api/registerUser/route.ts
  src/app/layout.tsx
  src/components/Login/Login.tsx
  src/components/Login/hooks/useLogin.ts
  src/components/UserInfoForm/UserInfoForm.tsx
  src/components/UserInfoForm/hooks/useRegister.ts
  src/hooks/useCurrentUser.ts
  src/hooks/useServerCookie.ts
  src/lib/contexts/AuthProvider.tsx
  src/lib/contexts/TanstackQueryContext.tsx
  src/services/auth/index.ts
  src/types/index.ts
Labels: ✨ Feature, 📬 API

#113 프로필 조회 api 연결
  src/app/(routes)/user/[userId]/layout.tsx
  src/app/(routes)/user/[userId]/page.tsx
  src/app/api/user/profile/[id]/route.ts
  src/components/common/Tab/hooks/useTab.ts
  src/components/common/Tab/utils/index.ts
  src/constants/index.ts
  src/data/index.ts
  src/hooks/useGetProfile.ts
  src/services/user/profile/profile.ts
  src/types/index.ts
  src/utils/index.ts
Labels: 📬 API

#112 스페이스 즐겨찾기 api 연결
  package-lock.json
  package.json
  src/app/(routes)/space/[spaceId]/comment/page.tsx
  src/app/(routes)/space/[spaceId]/page.tsx
  src/app/(routes)/user/[userId]/favorite/page.tsx
  src/app/(routes)/user/[userId]/space/page.tsx
  src/app/api/favorites/[spaceId]/route.ts
  src/app/api/link/route.ts
  src/app/api/space/[spaceId]/route.ts
  src/components/common/Modal/LoginModal.tsx
  src/components/common/Space/Space.tsx
  src/components/common/Space/hooks/useFavorites.ts
  src/constants/index.ts
  src/lib/fetchAPI.ts
  src/lib/fetchServerAPI.ts
  src/services/favorites/favorites.ts
  src/services/link/link.ts
  src/services/meta/meta.ts
  src/types/index.ts
Labels: 📬 API

#116 무한 스크롤 구현
  src/app/page.tsx
  src/components/SpaceList/SpaceList.tsx
  src/components/SpaceList/hooks/useSpacesQuery.ts
  src/components/index.ts
  src/constants/index.ts
  src/hooks/index.ts
  src/hooks/useCategoryParam.ts
  src/hooks/useHome.ts
  src/hooks/useInfiniteScroll.ts
  src/hooks/useQueryString.ts
  src/hooks/useSortParam.ts
Labels: ✨ Feature

#121 링크 좋아요 api 연결
  src/app/(routes)/user/[userId]/page.tsx
  src/app/api/link/like/route.ts
  src/app/page.tsx
  src/components/common/LinkItem/LinkItem.tsx
  src/components/common/LinkItem/hooks/useLikeLink.ts
  src/components/common/LinkList/LinkList.tsx
  src/components/common/Space/hooks/useFavorites.ts
  src/data/index.ts
  src/hooks/index.ts
  src/hooks/useCurrentModal.ts
  src/hooks/useModal.ts
  src/services/favorites/favorites.ts
  src/services/link/link.ts
  src/services/space/space.ts
Labels: 📬 API

#117 스페이스 세팅 api 연결
  src/app/(routes)/space/[spaceId]/setting/page.tsx
  src/app/api/registerUser/route.ts
  src/app/api/space/[spaceId]/route.ts
  src/app/api/spaces/create/route.ts
  src/components/Space/SpaceForm.tsx
  src/components/common/Tab/hooks/useTab.ts
  src/components/common/Tab/utils/index.ts
  src/lib/fetchAPI.ts
  src/lib/fetchServerAPI.ts
  src/services/link/link.ts
  src/services/space/space.ts
Labels: 📬 API

#126 [Release] v0.1.1
  .github/workflows/deploy.yml
Labels: 🌎 Deploy

#127 [Release] v0.1.1
  .github/workflows/deploy.yml
Labels: 🌎 Deploy

#128 스페이스 검색 api 연결
  src/app/(routes)/search/page.tsx
  src/app/api/spaces/search/route.ts
  src/components/common/CategoryList/hooks/useCategoryList.ts
  src/components/common/Dropdown/hooks/useDropdown.ts
  src/hooks/useSearch.ts
  src/services/space/spaces.ts
Labels: 📬 API

#130 로그아웃 API 연결
  src/app/api/logout/route.ts
  src/components/common/Sidebar/hooks/useSidebar.ts
  src/services/auth/index.ts
Labels: 📬 API

#138 유저 팔로우 api 연결
  src/app/(routes)/user/[userId]/page.tsx
  src/app/api/user/follow/route.ts
  src/app/api/user/profile/[id]/route.ts
  src/hooks/index.ts
  src/hooks/useFollowUser.ts
  src/services/user/follow/route.ts
Labels: 📬 API

#131 루트 댓글 조회 api 연결
  src/app/(routes)/space/[spaceId]/comment/page.tsx
  src/app/api/space/[spaceId]/comments/route.ts
  src/components/CommentList/CommentList.tsx
  src/components/CommentList/hooks/useCommentsQuery.ts
  src/components/common/Comment/Comment.tsx
  src/components/index.ts
  src/hooks/useSpaceComment.ts
  src/services/comment/comment.ts
  src/types/index.ts
Labels: 📬 API

#134 즐겨찾기 스페이스 검색 api 연결
  src/app/(routes)/user/[userId]/favorite/page.tsx
  src/app/(routes)/user/[userId]/space/page.tsx
  src/app/api/user/favorites/route.ts
  src/components/SpaceList/SpaceList.tsx
  src/components/SpaceList/constants/index.ts
  src/components/SpaceList/hooks/useSpacesQuery.ts
  src/hooks/index.ts
  src/hooks/useProfileFavoritesSearch.ts
  src/hooks/useSpaceSearch.ts
  src/services/space/spaces.ts
  src/services/user/profile/route.ts
  src/types/index.ts
Labels: 📬 API

#146 사이드바 로그인여부 적용 및 내 스페이스 api 연결
  src/app/api/user/[memberId]/spaces/route.ts
  src/components/Space/SpaceForm.tsx
  src/components/common/Sidebar/Sidebar.tsx
  src/components/common/Sidebar/hooks/useMySpace.ts
  src/services/space/spaces.ts
  src/types/index.ts
Labels: ✨ Feature, 📬 API

#147 대댓글 조회 api 연결
  src/app/api/space/[spaceId]/comments/[commentId]/replies/route.ts
  src/components/CommentList/CommentList.tsx
  src/components/CommentList/hooks/useCommentList.ts
  src/components/CommentList/hooks/useCommentsQuery.ts
  src/components/ReplyList/ReplyList.tsx
  src/components/ReplyList/constants/index.ts
  src/components/ReplyList/hooks/useRepliesQuery.ts
  src/services/comment/reply.ts
Labels: 📬 API

#136 링크 접속 정보 저장 api 연결
  src/app/api/space/[spaceId]/links/readInfo/route.ts
  src/components/common/LinkItem/LinkItem.tsx
  src/components/common/LinkItem/hooks/useReadSaveLink.ts
  src/services/link/link.ts
Labels: 📬 API

#148 프로필 스페이스 검색 api 연결
  src/app/(routes)/user/[userId]/favorite/page.tsx
  src/app/(routes)/user/[userId]/space/page.tsx
  src/app/api/user/[memberId]/spaces/route.ts
  src/components/SpaceList/SpaceList.tsx
  src/components/SpaceList/hooks/useSpacesQuery.ts
  src/components/common/Sidebar/hooks/useMySpace.ts
  src/hooks/index.ts
  src/hooks/useProfileSpacesSearch.ts
  src/services/space/spaces.ts
  src/types/index.ts
Labels: 📬 API

#152 댓글 삭제 api 연결
  src/app/(routes)/space/[spaceId]/comment/page.tsx
  src/app/api/space/[spaceId]/comments/[commentId]/route.ts
  src/components/CommentList/CommentList.tsx
  src/components/ReplyList/ReplyList.tsx
  src/components/common/Comment/Comment.tsx
  src/components/common/Comment/hooks/useComment.ts
  src/hooks/useSpaceComment.ts
  src/services/comment/comment.ts
  src/types/index.ts
Labels: 📬 API

#139 회원가입시 이메일 인증번호 발송, 인증번호 검증 api 연결
  src/app/api/email-verify/route.ts
  src/app/api/email/route.ts
  src/components/UserInfoForm/UserInfoForm.tsx
  src/components/common/Button/Button.tsx
  src/services/email/index.ts
Labels: 📬 API

#158 회원가입 오류 수정 (긴급)
  src/app/api/registerUser/route.ts
Labels: 🐞 Bug

#154 댓글 수정 api 연결
  src/app/(routes)/space/[spaceId]/comment/page.tsx
  src/app/api/space/[spaceId]/comments/[commentId]/route.ts
  src/components/CommentList/CommentList.tsx
  src/components/ReplyList/ReplyList.tsx
  src/components/common/Comment/Comment.tsx
  src/hooks/useSpaceComment.ts
  src/services/comment/comment.ts
  src/services/link/link.ts
Labels: 📬 API

#169 사이드바 즐겨찾기 스페이스 api 연결
  src/components/common/Sidebar/Sidebar.tsx
  src/components/common/Sidebar/hooks/useMySpace.ts
Labels: 📬 API

#163 유저 검색 api 연결
  src/app/(routes)/search/page.tsx
  src/app/api/user/search/route.ts
  src/components/UserList/UserList.tsx
  src/components/UserList/hooks/useUsersQuery.ts
  src/components/common/SearchModal/SearchModal.tsx
  src/components/common/SearchModal/constants/index.ts
  src/services/user/search/search.ts
  src/types/index.ts
Labels: 📬 API

#164 인기 링크 조회 api 연결
  src/app/api/links/route.ts
  src/app/page.tsx
  src/components/SpaceList/SpaceList.tsx
  src/components/common/Sidebar/Sidebar.tsx
  src/components/common/Tab/TabItem.tsx
  src/components/common/ThemeButton/ThemeButton.tsx
  src/hooks/useGetPopularLinks.ts
  src/services/link/link.ts
  src/types/index.ts
  tailwind.config.ts
Labels: 📬 API

#166 링크 수정 api 연결
  src/app/(routes)/space/[spaceId]/page.tsx
  src/app/api/space/[spaceId]/links/route.ts
  src/components/common/Input/Input.tsx
  src/components/common/LinkItem/LinkItem.tsx
  src/components/common/LinkItem/hooks/useDeleteLink.ts
  src/components/common/LinkItem/hooks/useReadSaveLink.ts
  src/components/common/LinkItem/hooks/useUpdateLink.ts
  src/components/common/LinkList/LinkList.tsx
  src/components/common/LinkList/constants/index.ts
  src/components/common/LinkList/hooks/useCreateLink.ts
  src/components/common/LinkList/hooks/useGetMeta.ts
  src/components/common/Modal/Modal.tsx
  src/components/common/Modal/hooks/useModalLogic.ts
  src/components/common/Space/hooks/useGetTags.ts
  src/components/common/SpaceMemberList/SpaceMemberList.tsx
  src/services/link/link.ts
Labels: 📬 API

#168 대댓글 생성 api 연결
  package-lock.json
  package.json
  src/app/(routes)/space/[spaceId]/comment/page.tsx
  src/app/api/space/[spaceId]/comments/[commentId]/replies/route.ts
  src/components/CommentList/CommentList.tsx
  src/components/CommentList/hooks/useCommentList.ts
  src/components/CommentList/hooks/useCommentsQuery.ts
  src/components/ReplyList/ReplyList.tsx
  src/components/ReplyList/hooks/useRepliesQuery.ts
  src/components/common/Comment/Comment.tsx
  src/hooks/useSpaceComment.ts
  src/services/comment/reply.ts
  src/utils/index.ts
Labels: ✨ Feature, 📬 API

#181 스페이스 초대 알림 조회 api 연결
  src/app/(routes)/notification/invite/page.tsx
  src/app/(routes)/notification/page.tsx
  src/app/api/notification/invitations/route.ts
  src/components/common/Header/Header.tsx
  src/components/common/Notification/Notification.tsx
  src/components/common/Notification/constants/index.ts
  src/components/common/NotificationList/NotificationList.tsx
  src/components/common/NotificationList/hooks/useNotificationQuery.ts
  src/components/common/Tab/constants/index.ts
  src/data/index.ts
  src/services/notification/invitations.ts
  src/types/index.ts
Labels: 📬 API

#175 스페이스 초대한 유저 권한 수정 api 연결
  src/app/api/space/[spaceId]/member/role/route.ts
  src/components/Space/SpaceForm.tsx
  src/components/common/Dropdown/Dropdown.tsx
  src/components/common/Dropdown/DropdownItem.tsx
  src/components/common/Dropdown/constants/index.ts
  src/components/common/SpaceMemberList/SpaceMemberList.tsx
  src/services/space/space.ts
Labels: 📬 API

#179 토스트 컴포넌트 구현
  package-lock.json
  package.json
  src/app/layout.tsx
  src/components/Space/SpaceForm.tsx
  src/components/common/Toast/Toast.tsx
  src/components/common/Toast/ToastContainer.tsx
Labels: ✨ Feature

#174 링크 관련 버튼 수정
  src/app/(routes)/space/[spaceId]/page.tsx
  src/components/common/LinkItem/LinkItem.tsx
  src/components/common/Modal/NoneServiceModal.tsx
Labels: ✨ Feature

#183 404 페이지 구현
  public/404.png
  src/app/not-found.tsx
  src/constants/index.ts
Labels: ✨ Feature

#185 모달 외부 스크롤이 동작하는 버그 수정
  src/components/common/Header/Header.tsx
  src/hooks/useModal.ts
Labels: 🐞 Bug

#186 스페이스폼, 유저폼 validation 추가
  src/components/Space/SpaceForm.tsx
  src/components/UserInfoForm/UserInfoForm.tsx
Labels: ✨ Feature

#190 스페이스 초대 수락 api 연결
  src/app/(routes)/bomiTest/buttonTest/page.tsx
  src/app/(routes)/bomiTest/tabTest/comment/page.tsx
  src/app/(routes)/bomiTest/tabTest/layout.tsx
  src/app/(routes)/bomiTest/tabTest/page.tsx
  src/app/(routes)/bomiTest/tabTest/setting/page.tsx
  src/app/api/spaces/invitation/route.ts
  src/components/common/NotificationList/NotificationList.tsx
  src/services/space/spaces.ts
  src/types/index.ts
Labels: 📬 API

#160 TagInput 컴포넌트 구현
  src/app/(routes)/space/[spaceId]/page.tsx
  src/app/globals.css
  src/components/TagInput/TagInput.tsx
  src/components/TagInput/hooks/useTagInput.ts
  src/components/common/LinkItem/LinkItem.tsx
  src/components/common/LinkList/LinkList.tsx
  src/components/common/Modal/Modal.tsx
  src/components/common/Modal/hooks/useModalLogic.ts
  src/types/index.ts
Labels: ✨ Feature

#187 스페이스 초대 api 연결
  src/app/(routes)/space/[spaceId]/page.tsx
  src/app/(routes)/space/[spaceId]/setting/page.tsx
  src/app/api/space/invitations/route.ts
  src/components/Space/SpaceForm.tsx
  src/components/common/SpaceMemberList/SpaceMemberList.tsx
  src/services/space/invitation.ts
  src/types/index.ts
Labels: 📬 API

#197 [Release] v0.1.3
  package-lock.json
  package.json
  public/404.png
  src/app/(routes)/bomiTest/buttonTest/page.tsx
  src/app/(routes)/bomiTest/tabTest/comment/page.tsx
  src/app/(routes)/bomiTest/tabTest/layout.tsx
  src/app/(routes)/bomiTest/tabTest/page.tsx
  src/app/(routes)/bomiTest/tabTest/setting/page.tsx
  src/app/(routes)/notification/invite/page.tsx
  src/app/(routes)/notification/page.tsx
  src/app/(routes)/space/[spaceId]/page.tsx
  src/app/(routes)/space/[spaceId]/setting/page.tsx
  src/app/api/notification/invitations/route.ts
  src/app/api/space/[spaceId]/member/role/route.ts
  src/app/api/space/invitations/route.ts
  src/app/api/spaces/invitation/route.ts
  src/app/globals.css
  src/app/layout.tsx
  src/app/not-found.tsx
  src/components/Space/SpaceForm.tsx
  src/components/TagInput/TagInput.tsx
  src/components/TagInput/hooks/useTagInput.ts
  src/components/UserInfoForm/UserInfoForm.tsx
  src/components/common/Dropdown/Dropdown.tsx
  src/components/common/Dropdown/DropdownItem.tsx
  src/components/common/Dropdown/constants/index.ts
  src/components/common/Header/Header.tsx
  src/components/common/LinkItem/LinkItem.tsx
  src/components/common/LinkList/LinkList.tsx
  src/components/common/Modal/Modal.tsx
  src/components/common/Modal/NoneServiceModal.tsx
  src/components/common/Modal/hooks/useModalLogic.ts
  src/components/common/Notification/Notification.tsx
  src/components/common/Notification/constants/index.ts
  src/components/common/NotificationList/NotificationList.tsx
  src/components/common/NotificationList/hooks/useNotificationQuery.ts
  src/components/common/SpaceMemberList/SpaceMemberList.tsx
  src/components/common/Tab/constants/index.ts
  src/components/common/Toast/Toast.tsx
  src/components/common/Toast/ToastContainer.tsx
  src/constants/index.ts
  src/data/index.ts
  src/hooks/useModal.ts
  src/services/notification/invitations.ts
  src/services/space/invitation.ts
  src/services/space/space.ts
  src/services/space/spaces.ts
  src/types/index.ts
Labels: 🌎 Deploy

#192 댓글 폼 validation 토스트 적용
  src/app/(routes)/space/[spaceId]/comment/page.tsx
  src/components/common/Comment/Comment.tsx
  src/components/common/Input/Input.tsx
  src/hooks/useSpaceComment.ts
Labels: ✨ Feature

#195 사이드바 애니메이션 구현
  src/app/layout.tsx
  src/components/common/Header/Header.tsx
  src/components/common/Sidebar/Sidebar.tsx
  src/components/common/Sidebar/hooks/useSidebar.ts
  tailwind.config.ts
Labels: 🎨 Style

#194 fetch error handler 추가
  src/app/(routes)/space/[spaceId]/setting/page.tsx
  src/app/api/space/[spaceId]/route.ts
  src/components/Space/SpaceForm.tsx
  src/components/UserInfoForm/UserInfoForm.tsx
  src/lib/fetchAPI.ts
  src/services/space/space.ts
Labels: ✨ Feature, 📬 API

#198 [Release] v0.1.4
  package-lock.json
  package.json
  src/app/(routes)/space/[spaceId]/comment/page.tsx
  src/app/(routes)/space/[spaceId]/page.tsx
  src/app/(routes)/space/[spaceId]/setting/page.tsx
  src/app/(routes)/user/[userId]/layout.tsx
  src/app/(routes)/user/[userId]/page.tsx
  src/app/api/space/[spaceId]/route.ts
  src/app/layout.tsx
  src/app/page.tsx
  src/components/Space/SpaceForm.tsx
  src/components/SpaceList/SpaceList.tsx
  src/components/SpaceList/hooks/useSpacesQuery.ts
  src/components/UserInfoForm/UserInfoForm.tsx
  src/components/UserList/UserList.tsx
  src/components/UserList/hooks/useUsersQuery.ts
  src/components/common/Comment/Comment.tsx
  src/components/common/FollowList/FollowList.tsx
  src/components/common/FollowList/hooks/useFollowQuery.ts
  src/components/common/Header/Header.tsx
  src/components/common/Input/Input.tsx
  src/components/common/LinkItem/LinkItem.tsx
  src/components/common/LinkList/LinkList.tsx
  src/components/common/LinkList/hooks/useLinksQuery.ts
  src/components/common/NotificationList/NotificationList.tsx
  src/components/common/NotificationList/hooks/useNotificationQuery.ts
  src/components/common/Sidebar/Sidebar.tsx
  src/components/common/Sidebar/hooks/useMySpace.ts
  src/components/common/Sidebar/hooks/useSidebar.ts
  src/components/common/Space/hooks/useGetSpace.ts
  src/components/common/Space/hooks/useGetTags.ts
  src/components/common/Spinner/Spinner.tsx
  src/components/index.ts
  src/hooks/useGetPopularLinks.ts
  src/hooks/useGetProfile.ts
  src/hooks/useSpaceComment.ts
  src/lib/fetchAPI.ts
  src/services/space/space.ts
  tailwind.config.ts
Labels: 🌎 Deploy
