Repository Team-TenTen/LinkHub-FE, pull requests merged in 2023-10, with the labels that each got.

#3 라우팅 설정
  .gitignore
  .husky/pre-commit
  .nvmrc
  package-lock.json
  package.json
  src/app/(routes)/login/page.tsx
  src/app/(routes)/notification/page.tsx
  src/app/(routes)/register/page.tsx
  src/app/(routes)/search/page.tsx
  src/app/(routes)/space/[spaceId]/comment/page.tsx
  src/app/(routes)/space/[spaceId]/page.tsx
  src/app/(routes)/space/[spaceId]/setting/page.tsx
  src/app/(routes)/space/create/page.tsx
  src/app/(routes)/user/[userId]/favorite/page.tsx
  src/app/(routes)/user/[userId]/page.tsx
  src/app/(routes)/user/[userId]/space/page.tsx
  src/app/(routes)/user/setting/page.tsx
  src/app/api/.gitkeep
Labels: ⚙ Setting

#6 초기 스타일 세팅
  .prettierrc
  package-lock.json
  package.json
  src/app/globals.css
  src/app/layout.tsx
  src/components/Providers/providers.tsx
  src/components/ThemeButton/themeButton.tsx
  src/components/index.ts
  src/utils/index.ts
  tailwind.config.ts
Labels: ⚙ Setting, ✨ Feature

#13 PR 워크플로 설정
  .github/workflows/pull_request.yml
Labels: ⚙ Setting

#16 공통 스타일 변수 세팅
  src/app/globals.css
  src/app/layout.tsx
  tailwind.config.ts
Labels: ⚙ Setting

#17 공통 스타일 이름 수정
  src/app/globals.css
  tailwind.config.ts
Labels: 🐞 Bug

#19 공통 스타일 이름 수정
  src/app/globals.css
  tailwind.config.ts
Labels: 🐞 Bug

#21 Avatar 컴포넌트 구현
  src/components/common/Avatar/Avatar.tsx
  src/components/common/AvatarGroup/AvatarGroup.tsx
  src/components/common/AvatarGroup/constants/index.ts
  src/components/index.ts
Labels: ✨ Feature

#23 Chip 컴포넌트 구현
  src/app/globals.css
  src/app/layout.tsx
  src/components/common/Chip/Chip.tsx
  src/components/common/Chip/constants/index.ts
  src/components/index.ts
  tailwind.config.ts
Labels: ✨ Feature

#24 탭 컴포넌트 구현
  src/app/(routes)/bomiTest/tabTest/comment/page.tsx
  src/app/(routes)/bomiTest/tabTest/layout.tsx
  src/app/(routes)/bomiTest/tabTest/page.tsx
  src/app/(routes)/bomiTest/tabTest/setting/page.tsx
  src/components/common/Tab/Tab.tsx
  src/components/common/Tab/TabItem.tsx
Labels: ✨ Feature

#25 Toggle 컴포넌트 구현
  src/components/common/Toggle/Toggle.tsx
  src/components/common/Toggle/hooks/useToggle.ts
  src/components/index.ts
Labels: ✨ Feature

#20 Input 컴포넌트 구현
  src/components/common/Input/Input.tsx
  src/components/common/Textarea/Textarea.tsx
  src/components/index.ts
  src/utils/index.ts
Labels: ✨ Feature

#28 next-theme 버그 수정
  src/components/Providers/Providers.tsx
  src/components/common/ThemeButton/ThemeButton.tsx
  src/components/index.ts
Labels: 🐞 Bug

#18 버튼 컴포넌트 구현
  src/app/(routes)/bomiTest/buttonTest/page.tsx
  src/app/globals.css
  src/components/common/Button/Button.tsx
Labels: ✨ Feature
