Repository Team-TenTen/LinkHub-FE, pull requests merged in 2023-12, with the labels that each got.

#201 사이드바 렌더링 오류 수정
  src/components/common/Sidebar/Sidebar.tsx
Labels: 🐞 Bug

#208 본인의 비공개 스페이스가 보이지 않는 오류 수정
  src/app/api/user/[memberId]/spaces/route.ts
Labels: 🐞 Bug

#211 링크 수정 폼 validation 오류 수정
  src/components/TagInput/TagInput.tsx
  src/components/common/Input/Input.tsx
  src/components/common/LinkItem/LinkItem.tsx
  src/components/common/LinkList/LinkList.tsx
  src/components/common/LinkList/constants/index.ts
Labels: 🐞 Bug

#215 모바일에서 인풋 클릭 시 줌인되는 현상 수정
  src/app/layout.tsx
Labels: ✨ Feature

#225 플로팅 버튼 구현
  src/app/page.tsx
  src/components/FloatingButton/FloatingButton.tsx
Labels: ✨ Feature

#216 스페이스 입력 폼 오류 수정
  src/app/(routes)/space/[spaceId]/page.tsx
  src/components/CommentList/CommentList.tsx
  src/components/Space/SpaceForm.tsx
  src/components/common/Space/Space.tsx
  src/components/common/Space/hooks/useGetSpace.ts
  src/components/common/Toggle/Toggle.tsx
  src/types/index.ts
Labels: 🐞 Bug

#203 알림 삭제 api 연결
  src/app/(routes)/notification/page.tsx
  src/app/api/notification/[notificationId]/route.ts
  src/components/SpaceList/SpaceList.tsx
  src/components/common/Notification/Notification.tsx
  src/components/common/NotificationList/NotificationList.tsx
  src/components/common/NotificationList/constants/index.ts
  src/components/common/NotificationList/hooks/useAcceptNotification.ts
  src/components/common/NotificationList/hooks/useDeleteNotification.ts
  src/components/common/NotificationList/hooks/useNotificationQuery.ts
  src/services/notification/index.ts
Labels: 📬 API

#218 링크 수정 버그 수정
  src/components/TagInput/TagInput.tsx
  src/services/link/link.ts
Labels: 🐞 Bug

#222 헤더 알림 뱃지 구현
  src/app/api/notification/unchecked/route.ts
  src/components/common/Header/Header.tsx
  src/components/common/Header/hooks/useHeader.ts
  src/services/notification/invitations.ts
Labels: ✨ Feature

#230 팔로우 버튼 클릭 시 이전 데이터가 일시적으로 보이는 문제 수정
  public/duck.jpg
  public/member-default.png
  src/components/common/FollowList/hooks/useFollowQuery.ts
  src/components/common/LinkItem/LinkItem.tsx
  src/components/common/User/User.tsx
  src/hooks/useFollowUser.ts
Labels: ✨ Feature

#234 스페이스 초대 토스트 적용
  src/components/common/SpaceMemberList/SpaceMemberList.tsx
Labels: ✨ Feature

#233 에러처리 수정 및 접근 제한 추가
  src/lib/contexts/AuthProvider.tsx
  src/lib/fetchAPI.ts
  src/middleware.ts
Labels: 🐞 Bug, ✨ Feature

#235 버튼 디바운스 딜레이 수정
  src/components/common/LinkItem/hooks/useLikeLink.ts
  src/components/common/Space/hooks/useFavorites.ts
  src/hooks/useFollowUser.ts
Labels: ✨ Feature

#232 헤더 오류 수정
  src/components/common/Header/Header.tsx
  src/components/common/Header/constants/index.ts
  src/components/common/Header/hooks/useHeader.ts
Labels: 🐞 Bug

#206 유저정보 form 버그 수정
  src/components/Login/Login.tsx
  src/components/UserInfoForm/UserInfoForm.tsx
  src/components/UserInfoForm/hooks/useRegister.ts
  src/components/common/Input/Input.tsx
  src/components/common/Sidebar/hooks/useSidebar.ts
  src/lib/fetchAPI.ts
  src/services/email/index.ts
Labels: 🐞 Bug

#250 Dropdown, Comment 컴포넌트 UI 수정
  src/components/common/Comment/Comment.tsx
  src/components/common/Dropdown/Dropdown.tsx
  src/components/common/Input/Input.tsx
Labels: 🎨 Style

#255 CategoryList 컴포넌트 슬라이드 적용
  src/app/globals.css
  src/components/common/CategoryList/CategoryList.tsx
  src/components/common/CategoryList/CategoryListItem.tsx
  src/components/common/Sidebar/Sidebar.tsx
Labels: ✨ Feature

#251 링크 생성, 수정 폼 validation 조건 추가
  src/components/common/LinkItem/LinkItem.tsx
  src/components/common/LinkItem/hooks/useLikeLink.ts
  src/components/common/LinkList/LinkList.tsx
  src/components/common/LinkList/constants/index.ts
  src/components/common/LinkList/hooks/useGetMeta.ts
Labels: ✨ Feature

#254 유저 정보 입력 폼 오류 수정
  src/app/layout.tsx
  src/components/Login/Login.tsx
  src/components/UserInfoForm/UserInfoForm.tsx
  src/components/UserInfoForm/hooks/useRegister.ts
Labels: 🐞 Bug

#244 메타데이터 추가
  src/app/(routes)/login/page.tsx
  src/app/(routes)/notification/layout.tsx
  src/app/(routes)/register/page.tsx
  src/app/(routes)/search/page.tsx
  src/app/(routes)/space/[spaceId]/layout.tsx
  src/app/(routes)/space/create/page.tsx
  src/app/(routes)/user/[userId]/layout.tsx
  src/app/(routes)/user/setting/page.tsx
  src/app/favicon.ico
  src/app/layout.tsx
  src/app/opengraph-image.png
  src/app/twitter-image.png
  src/components/NotificationController/NotificationController.tsx
  src/components/SearchController/SearchController.tsx
  src/components/SettingController/SettingController.tsx
  src/components/UserController/UserController.tsx
  src/components/index.ts
Labels: ✨ Feature

#243 스페이스 입력 폼 오류 수정
  src/components/Space/SpaceForm.tsx
Labels: 🐞 Bug

#258 CategoryList 컴포넌트 버그 수정
  src/components/SearchController/SearchController.tsx
  src/components/UserList/UserList.tsx
  src/components/common/CategoryList/CategoryListItem.tsx
  src/components/common/Space/Space.tsx
Labels: 🐞 Bug

#266 메타데이터 수정
  src/app/layout.tsx
  src/app/opengraph-image.png
  src/app/twitter-image.png
Labels: ✨ Feature

#260 인기 링크 리스트 좋아요 버튼 오류 수정
  src/components/common/LinkItem/hooks/useLikeLink.ts
Labels: 🐞 Bug

#267 드롭다운 목록 스타일 수정
  src/components/TagInput/TagInput.tsx
  src/components/common/Dropdown/Dropdown.tsx
  src/components/common/Sidebar/Sidebar.tsx
Labels: 🎨 Style

#273 Sidebar 컴포넌트 스타일 수정
  src/components/common/Sidebar/Sidebar.tsx
Labels: 🎨 Style

#277 open-graph-scraper 예외 추가
  src/app/api/meta/route.ts
  src/components/common/LinkItem/LinkItem.tsx
  src/components/common/LinkItem/hooks/useDeleteLink.ts
  src/components/common/LinkItem/hooks/useUpdateLink.ts
  src/components/common/LinkList/LinkList.tsx
  src/components/common/LinkList/hooks/useCreateLink.ts
  src/components/common/LinkList/hooks/useGetMeta.ts
Labels: ✨ Feature, 📬 API

#280 스페이스 생성 시 카테고리 필수 알림 추가
  src/components/Space/SpaceForm.tsx
  src/components/common/Space/Space.tsx
Labels: ✨ Feature

#281 [Release] v0.1.9
  src/components/Space/SpaceForm.tsx
  src/components/common/Space/Space.tsx
Labels: 🌎 Deploy
