Repository Team-TenTen/LinkHub-FE, pull requests merged in 2024-03, with the labels that each got.

#292 chore: images 경로 수정
  next.config.js
Labels: ⚙ Setting

#293 deploy.yml 수정
  .github/workflows/deploy.yml
Labels: 🌎 Deploy

#294 appspec.yml 수정
  appspec.yml
Labels: 🌎 Deploy

#295 sharp 라이브러리 설치
  package-lock.json
  package.json
Labels: ✨ Feature

#296 Metadata images 경로 수정
  src/app/layout.tsx
Labels: ⚙ Setting
