Repository Team-TenTen/LinkHub-FE, pull requests merged in 2024-07, with the labels that each got.

#310 스켈레톤 UI 개발 및 적용
  src/app/(routes)/space/[spaceId]/page.tsx
  src/app/page.tsx
  src/components/common/LinkItem/LinkItemSkeleton.tsx
  src/components/common/MainSpaceList/MainSpaceList.tsx
  src/components/common/MainSpaceList/MainSpaceSkeleton.tsx
  src/components/common/Skeleton/Skeleton.tsx
  src/components/common/Space/SpaceSkeleton.tsx
Labels: ✨ Feature, 🔨 Refactor

#314 1차 라이트하우스 기반 성능 개선 작업
  package-lock.json
  package.json
  src/app/(routes)/space/[spaceId]/page.tsx
  src/app/globals.css
  src/app/layout.tsx
  src/app/page.tsx
  src/components/common/FollowList/FollowList.tsx
  src/components/common/LinkItem/LinkItemSkeleton.tsx
  src/components/common/MainSpaceList/MainSpaceList.tsx
  src/components/common/MainSpaceList/MainSpaceSkeleton.tsx
  src/components/common/Skeleton/Skeleton.tsx
  src/components/common/Space/SpaceSkeleton.tsx
  src/static/font/PretendardVariable.woff2
Labels: 🔨 Refactor

#313 반응형 스타일 구현
  src/app/(routes)/notification/layout.tsx
  src/app/(routes)/search/layout.tsx
  src/app/(routes)/space/[spaceId]/comment/page.tsx
  src/app/(routes)/space/[spaceId]/page.tsx
  src/app/(routes)/user/[userId]/layout.tsx
  src/app/layout.tsx
  src/app/page.tsx
  src/components/FloatingButton/FloatingButton.tsx
  src/components/Login/Login.tsx
  src/components/Space/SpaceForm.tsx
  src/components/common/Header/Header.tsx
  src/components/common/MainSpaceList/MainSpaceList.tsx
  src/components/common/Modal/Modal.tsx
  src/components/common/SearchModal/SearchModal.tsx
  src/components/common/Sidebar/Sidebar.tsx
Labels: ✨ Feature, 🔨 Refactor, 🎨 Style

#315 js 번들링 사이즈 감소
  .gitignore
  next.config.js
  package-lock.json
  package.json
  src/app/(routes)/notification/page.tsx
  src/app/(routes)/space/[spaceId]/comment/page.tsx
Labels: 🔨 Refactor

#316 [Release] v0.1.13
  .gitignore
  next.config.js
  package-lock.json
  package.json
  src/app/(routes)/notification/layout.tsx
  src/app/(routes)/notification/page.tsx
  src/app/(routes)/search/layout.tsx
  src/app/(routes)/space/[spaceId]/comment/page.tsx
  src/app/(routes)/space/[spaceId]/page.tsx
  src/app/(routes)/space/[spaceId]/setting/page.tsx
  src/app/(routes)/user/[userId]/layout.tsx
  src/app/globals.css
  src/app/layout.tsx
  src/app/page.tsx
  src/components/FloatingButton/FloatingButton.tsx
  src/components/Login/Login.tsx
  src/components/ProfileEditButton/ProfileEditButton.tsx
  src/components/Space/SpaceForm.tsx
  src/components/SpaceList/SpaceList.tsx
  src/components/UserList/UserList.tsx
  src/components/common/CategoryList/CategoryList.tsx
  src/components/common/CategoryList/CategoryListItem.tsx
  src/components/common/Comment/Comment.tsx
  src/components/common/DeferedComponent/DeferedComponent.tsx
  src/components/common/FollowList/FollowList.tsx
  src/components/common/Header/Header.tsx
  src/components/common/LinkItem/LinkItem.tsx
  src/components/common/LinkList/LinkList.tsx
  src/components/common/MainSpaceList/MainSpaceList.tsx
  src/components/common/Modal/Modal.tsx
  src/components/common/NotificationList/NotificationList.tsx
  src/components/common/SearchModal/SearchModal.tsx
  src/components/common/Sidebar/Sidebar.tsx
  src/components/common/Space/Space.tsx
  src/static/font/PretendardVariable.woff2
Labels: 🌎 Deploy

#318 Feature/#317/main css bug
  src/app/page.tsx
  src/components/common/MainSpaceList/MainSpaceList.tsx
Labels: 🐞 Bug, 🎨 Style

#319 [Release] v0.1.14
  src/app/page.tsx
  src/components/common/MainSpaceList/MainSpaceList.tsx
Labels: 🌎 Deploy

#322 2차 라이트하우스 기반 성능 개선 작업
  next.config.js
  src/app/not-found.tsx
  src/components/Space/SpaceForm.tsx
  src/components/common/Avatar/Avatar.tsx
  src/components/common/CategoryList/CategoryListItem.tsx
  src/components/common/Comment/Comment.tsx
  src/components/common/Header/Header.tsx
  src/components/common/LinkItem/LinkItem.tsx
  src/components/common/SearchModal/SearchModal.tsx
  src/components/common/SearchModal/hooks/useSearchModal.ts
  src/components/common/Sidebar/Sidebar.tsx
  src/components/common/Space/Space.tsx
  src/components/common/Tab/TabItem.tsx
  src/components/common/User/User.tsx
  src/data/index.ts
Labels: 🔨 Refactor
